---
- hosts: spigushe
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: spigushe

  roles:
    - role: register-ssl
      tags:
        - frontend
        - certs
      rs_server_name: barrins-codex.org

    - role: register-ssl
      tags:
        - frontend
        - certs
      rs_server_name: www.barrins-codex.org

    - role: flask-backend
      tags:
        - backend
        - uwsgi
      fb_package: barrins-codex
      fb_uwsgi_entrypoint: "barrins_codex:app"
      fb_server_name: barrins-codex.org
      fb_port: 8002

    - role: backend-website
      tags: backend
      pw_server_name: barrins-codex.org
      pw_alternate_server_name: www.barrins-codex.org
      pw_port: 8002
