---
- hosts: spigushe
  become: "yes"
  gather_facts: "no"

  vars:
    username: spigushe

  roles:
    - role: register-ssl
      tags:
        - frontend
        - certs
      rs_server_name: spigushe.com

    - role: static-website
      tags: frontend
      sw_server_name: spigushe.com

  post_tasks:
    - name: Clone static index.html
      copy:
        src: ./static/front/index.html
        dest: /home/spigushe/projects/spigushe.com/dist
        remote_src: no
        owner: spigushe
        mode: 0644

    - name: restart NGINX
      service:
        name: nginx
        state: reloaded
