---
- hosts: spigushe
  become: 'yes'
  gather_facts: 'no'

  vars:
    username: spigushe

  roles:
    - role: register-ssl
      tags:
        - frontend
        - certs
      rs_server_name: ligue.spigushe.com

    - role: php-backend
      tags: backend
      pb_server_name: ligue.spigushe.com

    - role: ligue-deploy
      tags: backend
      ld_server_name: ligue.spigushe.com
      ld_repo: Spigushe/LigueSite.git
