---
- name: Clone git repository
  git:
    repo: 'https://github.com/{{ gd_repo }}'
    dest: "/home/{{ username }}/projects/{{ gd_server_name }}/dist"
    update: yes

- name: Change file ownership, group and permissions
  file:
    state: directory
    path: "/home/{{ username }}/projects/{{ gd_server_name }}"
    owner: "www-data"
    group: "www-data"
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
