---
- name: Update APT packages
  apt:
    update_cache: "yes"
    cache_valid_time: "3600"
    upgrade: full

- name: Installing Required PHP Packages
  apt:
    state: present
    name:
      - git
      - mcrypt
      - nginx
      - php{{ r.php_default_version }}-cli
      - php{{ r.php_default_version }}-curl
      - php{{ r.php_default_version }}-fpm
      - php{{ r.php_default_version }}-intl
      - php{{ r.php_default_version }}-json
      - php-sqlite3

- name: Systemen Files | ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/{{ r.php_default_version }}/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0

- name: Add HTTPS site configuration
  template:
    src: https.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ r.server_name }}.https.conf"

- name: Ensure site root folder is present
  file:
    state: directory
    path: "{{ r.site_root }}/dist"
    owner: "{{ username }}"
    mode: 0755

- name: Reload php
  service:
    name: php{{ r.php_default_version }}-fpm
    state: reloaded

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
